version: "4.23.0"

services:
  postgresdb:
    image: postgres:16
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DATABASE_DB
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - db:/var/lib/postgresql/data
  app:
    depends_on:
      - postgresdb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DATABASE_HOST=postgresdb
      - DATABASE_PORT=$POSTGRES_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db:
